apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: hello
  namespace: camel-k
spec:
  sources:
    - name: Hello.java
      content: |
        // camel-k: language=java
        import org.apache.camel.builder.RouteBuilder;

        public class Hello extends RouteBuilder {
            @Override
            public void configure() throws Exception {
                from("timer:tick?period=2000")
                  .setBody().constant("Hello Camel-K!")
                  .to("log:info");
            }
        }
