apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: helloworld-inline
spec:
  sources:
    - name: HelloworldInline.java
      language: java
      content: |
        import org.apache.camel.builder.RouteBuilder;
        public class HelloworldInline extends RouteBuilder {
            @Override
            public void configure() {
                from("timer:inline")
                    .setBody().simple("Hello Camel from ${routeId} (inline)")
                    .log("${body}");
            }
        }
